<?php

/**
 * BasePackage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $TransportLoad
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method Doctrine_Collection getTransportLoad() Returns the current record's "TransportLoad" collection
 * @method Package             setName()          Sets the current record's "name" value
 * @method Package             setTransportLoad() Sets the current record's "TransportLoad" collection
 * 
 * @package    transzam
 * @subpackage model
 * @author     Hans Rip
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePackage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('package');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TransportLoad', array(
             'local' => 'id',
             'foreign' => 'package_id'));
    }
}