<?php

/**
 * BaseDistrict
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $province_id
 * @property Province $Province
 * @property Doctrine_Collection $User
 * @property Doctrine_Collection $TransportLoad
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method integer             getProvinceId()    Returns the current record's "province_id" value
 * @method Province            getProvince()      Returns the current record's "Province" value
 * @method Doctrine_Collection getUser()          Returns the current record's "User" collection
 * @method Doctrine_Collection getTransportLoad() Returns the current record's "TransportLoad" collection
 * @method District            setName()          Sets the current record's "name" value
 * @method District            setProvinceId()    Sets the current record's "province_id" value
 * @method District            setProvince()      Sets the current record's "Province" value
 * @method District            setUser()          Sets the current record's "User" collection
 * @method District            setTransportLoad() Sets the current record's "TransportLoad" collection
 * 
 * @package    transzam
 * @subpackage model
 * @author     Hans Rip
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDistrict extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('district');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('province_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Province', array(
             'local' => 'province_id',
             'foreign' => 'id'));

        $this->hasMany('User', array(
             'local' => 'id',
             'foreign' => 'district_id'));

        $this->hasMany('TransportLoad', array(
             'local' => 'id',
             'foreign' => 'from_district'));
    }
}