<?php

/**
 * BaseCustomer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $CustomerPreferredTransporter
 * @property Doctrine_Collection $TransportLoad
 * 
 * @method Doctrine_Collection getCustomerPreferredTransporter() Returns the current record's "CustomerPreferredTransporter" collection
 * @method Doctrine_Collection getTransportLoad()                Returns the current record's "TransportLoad" collection
 * @method Customer            setCustomerPreferredTransporter() Sets the current record's "CustomerPreferredTransporter" collection
 * @method Customer            setTransportLoad()                Sets the current record's "TransportLoad" collection
 * 
 * @package    transzam
 * @subpackage model
 * @author     Hans Rip
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCustomer extends User
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CustomerPreferredTransporter', array(
             'local' => 'id',
             'foreign' => 'customer_id'));

        $this->hasMany('TransportLoad', array(
             'local' => 'id',
             'foreign' => 'customer_id'));
    }
}