<?php

/**
 * BaseExtendedCustomer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $PreferredTransporters
 * 
 * @method Doctrine_Collection getPreferredTransporters() Returns the current record's "PreferredTransporters" collection
 * @method ExtendedCustomer    setPreferredTransporters() Sets the current record's "PreferredTransporters" collection
 * 
 * @package    transzam
 * @subpackage model
 * @author     Hans Rip
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExtendedCustomer extends Customer
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Transporter as PreferredTransporters', array(
             'refClass' => 'CustomerPreferredTransporter',
             'local' => 'customer_id',
             'foreign' => 'transporter_id'));
    }
}