<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $username
 * @property string $password
 * @property integer $mobile_number
 * @property string $token
 * @property integer $number_of_trucks
 * 
 * @method string  getName()             Returns the current record's "name" value
 * @method string  getUsername()         Returns the current record's "username" value
 * @method string  getPassword()         Returns the current record's "password" value
 * @method integer getMobileNumber()     Returns the current record's "mobile_number" value
 * @method string  getToken()            Returns the current record's "token" value
 * @method integer getNumberOfTrucks()   Returns the current record's "number_of_trucks" value
 * @method User    setName()             Sets the current record's "name" value
 * @method User    setUsername()         Sets the current record's "username" value
 * @method User    setPassword()         Sets the current record's "password" value
 * @method User    setMobileNumber()     Sets the current record's "mobile_number" value
 * @method User    setToken()            Sets the current record's "token" value
 * @method User    setNumberOfTrucks()   Sets the current record's "number_of_trucks" value
 * 
 * @package    transzam
 * @subpackage model
 * @author     Hans Rip
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('login as username', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mobile_number', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('number_of_trucks', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}