<?php

/**
 * BaseCustomerPreferredTransporter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $customer_id
 * @property integer $transporter_id
 * @property Customer $Customer
 * @property Transporter $Transporter
 * 
 * @method integer                      getCustomerId()     Returns the current record's "customer_id" value
 * @method integer                      getTransporterId()  Returns the current record's "transporter_id" value
 * @method Customer                     getCustomer()       Returns the current record's "Customer" value
 * @method Transporter                  getTransporter()    Returns the current record's "Transporter" value
 * @method CustomerPreferredTransporter setCustomerId()     Sets the current record's "customer_id" value
 * @method CustomerPreferredTransporter setTransporterId()  Sets the current record's "transporter_id" value
 * @method CustomerPreferredTransporter setCustomer()       Sets the current record's "Customer" value
 * @method CustomerPreferredTransporter setTransporter()    Sets the current record's "Transporter" value
 * 
 * @package    transzam
 * @subpackage model
 * @author     Hans Rip
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCustomerPreferredTransporter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('customer_preferred_transporter');
        $this->hasColumn('customer_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('transporter_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Customer', array(
             'local' => 'customer_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Transporter', array(
             'local' => 'transporter_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}