<?php

/**
 * BaseProvince
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $District
 * 
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getDistrict() Returns the current record's "District" collection
 * @method Province            setName()     Sets the current record's "name" value
 * @method Province            setDistrict() Sets the current record's "District" collection
 * 
 * @package    transzam
 * @subpackage model
 * @author     Hans Rip
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProvince extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('province');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('District', array(
             'local' => 'id',
             'foreign' => 'province_id'));
    }
}