sf_guard_user_group:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUserGroup
    module:               sf_guard_user_group
    prefix_path:          /sf_guard_user_group
    column:               Array
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               sf_guard_user
    prefix_path:          /sf_guard_user
    column:               id
    with_wildcard_routes: true

transport_load:
  class: sfDoctrineRouteCollection
  options:
    model:                TransportLoad
    module:               transport_load
    prefix_path:          /transport_load
    column:               id
    with_wildcard_routes: true

extended_customer:
  class: sfDoctrineRouteCollection
  options:
    model:                ExtendedCustomer
    module:               extended_customer
    prefix_path:          /extended_customer
    column:               id
    with_wildcard_routes: true

transporter:
  class: sfDoctrineRouteCollection
  options:
    model:                Transporter
    module:               transporter
    prefix_path:          /transporter
    column:               id
    with_wildcard_routes: true

customer:
  class: sfDoctrineRouteCollection
  options:
    model:                Customer
    module:               customer
    prefix_path:          /customer
    column:               id
    with_wildcard_routes: true

province:
  class: sfDoctrineRouteCollection
  options:
    model:                Province
    module:               province
    prefix_path:          /province
    column:               id
    with_wildcard_routes: true

district:
  class: sfDoctrineRouteCollection
  options:
    model:                District
    module:               district
    prefix_path:          /district
    column:               id
    with_wildcard_routes: true

package:
  class: sfDoctrineRouteCollection
  options:
    model:                Package
    module:               package
    prefix_path:          /package
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
