<?php

/**
 * AdminSettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    transzam
 * @subpackage model
 * @author     Hans Rip
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * @abstract   AdminSettings creates a singleton with 1 record of adminsetting values.
 */
class AdminSettings extends BaseAdminSettings
{
}