<?php

/**
 * TransportLoad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    transzam
 * @subpackage model
 * @author     Hans Rip
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TransportLoad extends BaseTransportLoad
{
public function save(Doctrine_Connection $conn = null)
  {
    if ($this->isNew() && !$this->getExpiredAt())
    {
      /* ExpiredAt adds 30 days after the ArriveAfter date.
       * TODO : 30 days is now a fixed duration. Should be a administrator value which should be maintained via a Class.
       */
      $now = $this->getArriveAfter() ? $this->getDateTimeObject('created_at')->format('U') : time();
      
      $this->setExpiredAt(date('Y-m-d H:i:s', $now + 86400 * AdminSettingsTable::getInstance()->get('TransportloadExpirationInDays')));


    }

    return parent::save($conn);
  }

}