all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=transzam'
      username: root
      password: Hell0W0rld
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=transzam_test'
      username: root
      password: Hell0W0rld
