<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/05/04 09:22:39

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=transzam_test',
  'username' => 'root',
  'password' => 'Hell0W0rld',
  'name' => 'doctrine',
)),);
