<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/04/29 13:15:42

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=transzam',
  'username' => 'root',
  'password' => 'Hell0W0rld',
  'name' => 'doctrine',
)),);
