# Detect relations between the tables
detect_relations: true

# TranszamPackage has different kind of PackType, like bags, container, pallets, cooling, other, etc
Package:
  columns:
   name: { type: string(50) }

# TranszamProvince describes the provinces
Province:
  columns:
    name: { type: string(50) }

# TranszamDistrict describes all the districts
District:
  columns:
   name: { type: string(50) }
   province_id: { type: integer, notnull: true }

# TranszamUser describes the userdetails

# User
User:
  columns:
    sf_guard_user_id: { type : integer(4) }
    company: { type: string(255) }
    district_id: { type: integer }
    address: { type: string(255) }
    email_address: { type: string(255) }
    tel: { type: string(255) }
    cell: { type: string(255) }
    comment: { type: string(255) }
    # Two additional "login" names.
    sms_number: { type: integer }
  relations:
    GuardUser:
        class: sfGuardUser
        foreignType: one

# TranszamTransporter describes the transporter
Transporter:
  inheritance:
    extends: User
    type: column_aggregation
    keyField: user_type
    keyValue: transporter
  columns:
    number_of_trucks : { type : integer }

# TanszamCustomer describes the customer
Customer:
  inheritance:
    extends : User
    type: column_aggregation
    keyField : user_type
    keyValue : customer
  columns:
    business: { type : string(255) }

ExtendedCustomer :
  inheritance:
    extends: Customer
    type : column_aggregation
    keyField: user_type
    keyValue: customer
  relations:
    PreferredTransporters:
      class: Transporter
      refClass: CustomerPreferredTransporter
      local: customer_id
      foreign: transporter_id
      foreignAlias: Transporters

# Een customer met preffered transporters
CustomerPreferredTransporter:
  columns:
    customer_id:  { type: integer, primary: true }
    transporter_id: { type: integer, primary: true }
  relations:
    Customer:  { onDelete: CASCADE, local: customer_id, foreign: id }
    Transporter: { onDelete: CASCADE, local: transporter_id, foreign: id }


# TranszamTransportLoad has loads from the customer to the transporter.
TransportLoad:
  actAs: {Timestampable: ~ }
  columns:
    customer_id: { type: integer, notnull: true }
    transporter_id: { type: integer, notnull: true }
    from_district: { name: from_district as from, type: integer, notnull: true }
    to_district: { name: to_district as to, type: integer, notnull: true }
    load_description: { type: string(50) }
    package_id: { type: string(50), notnull: true }
    weight: { type: int, notnull: true, default: 0 }
    arrive_before: { type: timestamp, notnull: true }
    arrive_after: { type: timestamp }
    expired_at: { type: timestamp }
    bid: { type: enum, length: 9, values: [ 'Open', 'Taken', 'Cancelled' ], default: 'Open' }
    comment: { type: string(255) }
  relations:
      FromDistrict: 
        class: District
        local: from_district
        foreign: id
      ToDistrict:
        class: District
        local: to_district
        foreign: id


# TranszamTransportLoad has loads from the customer to the transporter.
AdminSettings:
  actAs: {Timestampable: ~ }
  columns:
    transportload_expiration_in_days: { type: timestamp, notnull: true }

