<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../config/ProjectConfiguration.class.php';

/**
 * Test class for ProjectConfiguration.
 * Generated by PHPUnit on 2010-05-06 at 18:55:35.
 */
class ProjectConfigurationTest extends PHPUnit_Framework_TestCase {
    /**
     * @var ProjectConfiguration
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ProjectConfiguration;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testSetup().
     */
    public function testSetup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
